# Generated by Django 5.2.1 on 2025-05-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0003_alter_comment_content_alter_event_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('normal', 'Normal'), ('survey', 'Survey'), ('announcement', 'Announcement')], default='normal', max_length=30),
        ),
    ]
